### ISSUE TITLE
Cookie statement

### ISSUE THREAD

**Issue by MichielB79** [JustCarmen/justlight#25]
Hi Carmen,

On your own website I see you have a cookie statement on the bottom of the page. I can't find a setting for this in webtrees. Is this custom made or am I missing a setting.

Thank you!

Michiel

**Comment by JustCarmen** [comment]
The cookie statement is a default webtrees item and is implemented in every standard webtrees theme and in the JustLight and JustBlack theme since webtrees version 1.7.4. I don't know if other theme authors have implement this function in there themes.

The cookie statement is shown only when all of the following conditions are true:
- You use one of the tracking facilities (google analytics, piwik or statcounter). See control panel - website - tracking and analytics;
- you haven't set the 'do not track' option in your browser, indicating that you don't want to be tracked by certain websites;
- You haven't clicked off the cookie statement before. When clicking off the cookie statement a cookie will hold this information until session cookies are cleared. This prevents a user seeing the statement at every page refresh.

So my guess is you don't use any tracking facilities and that's why you don't see the cookie statement.

**Comment by MichielB79** [comment]
I use google analytics. I have deleted and reinstalled the theme, and it's working now. Thanks for your quick response!
