### ISSUE TITLE
RFE: Panels as tabs

### ISSUE THREAD

**Issue by bmhm** [JustCarmen/justlight#28]
Hi Carmen,

I'd like to have an option to display the panels in a traditional tab style. At the moment, only the accordeon style is possible.

Example of what I mean:
https://github.com/flatlogic/bootstrap-tabcollapse (see Demo link).

Another implementation with icons:
https://github.com/openam/bootstrap-responsive-tabs

Even another without any plugins:
https://codepen.io/TrailRunner65/pen/kqiFI

Thank you very much. :-) :+1:

**Comment by e-LUNATIC** [comment]
I agree to the suggestion. Tabs are much better.

**Comment by JustCarmen** [comment]
At the time I wrote this theme, panels were the best way to achieve responsiveness within webtrees. I agree with you there are better solutions now.

At the moment webtrees is undertaking a major rewrite (webtrees 2.0 development). One of the major changes will be the introduction of Bootstrap 4 as the main layout system. With the introduction of Bootstrap 4 theme styling will become much easier, although it means a major rewrite of this theme. Since a rewrite is inevitable, I will reconsider some solutions. One of the things I have in mind is to reconsider the current panel system for the individual page and investigate the use of tabs again. But these changes have to wait until the webtrees 2.0 release.

**Comment by JustCarmen** [comment]
Like webtrees 2.0.0 this theme uses tabs on the individual page now. Panels are not supported by bootstrap anymore.
