### ISSUE TITLE
Compatibility with Webtrees 2

### ISSUE THREAD

**Issue by imskriaz** [JustCarmen/justlight#30]
I have installed webtrees dev version 2 from github. It seems this theme is not working with the same.

It will be great if this theme works with webtrees version 2 as I dont want to miss a beautiful theme in forward.

**Comment by JustCarmen** [comment]
I am working on it, but since webtrees is undergoing such major changes and things are changing back- and forward I have not placed a development version in the repository yet. But it is a matter of time before I can upload the first raw version. 

My goal is to get the theme ready for webtrees 2.0.

**Comment by JustCarmen** [comment]
Just uploaded a webtrees 2.0.0 compatible theme. It is still in development though.
